version = 0.1
[default.deploy.parameters]
stack_name = "sample"
resolve_s3 = true
s3_prefix = "sample"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "ApplicationName=sample",
    "GlueDatabaseName=dynamodb",
    "GlueTableName=sample"
]
image_repositories = []

