version = 0.1
[default.deploy.parameters]
stack_name = "pronunciation-check"
resolve_s3 = true
s3_prefix = "pronunciation-check"
region = "ap-northeast-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "ApplicationName=pronunciation-check"
]
image_repositories = []
